# Generated by Django 4.1.3 on 2022-11-13 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('nro', models.IntegerField(primary_key=True, serialize=False)),
                ('dueño', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Entregado')], default='P', max_length=1)),
                ('fechaRecepcion', models.DateField()),
                ('conserje', models.ForeignKey(limit_choices_to={'groups__name': 'conserje'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nroResidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
